// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xibtzulhjufpxbayiohq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpYnR6dWxoanVmcHhiYXlpb2hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NjQ5ODksImV4cCI6MjA2MjQ0MDk4OX0.0oQ3UJBjU7KeZjOMceILCTta5KaPRCQyeTRbQjVrvos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);